<?php
/**
 * Created by PhpStorm.
 * User: vadim
 * Date: 14.02.16
 * Time: 14:36
 */

namespace app\controllers;


use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\filters\VerbFilter;

class StandartController extends Controller
{
    public $model = null;
    public $searchModel = null;

    public $defaultAction = 'list';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actions()
    {
        $actions = [
            'list' => ['class' => 'app\controllers\actions\ListAction'],
            'copy' => ['class' => 'app\controllers\actions\CopyAction'],
            'update' => ['class' => 'app\controllers\actions\UpdateAction'],
            'unlock' => ['class' => 'app\controllers\actions\UnlockAction'],
            'lock' => ['class' => 'app\controllers\actions\LockAction'],
            'delete' => ['class' => 'app\controllers\actions\DeleteAction'],
        ];
        return ArrayHelper::merge($actions, parent::actions()); // TODO: Change the autogenerated stub
    }

    public function getLayouts()
    {
        $layouts = scandir(\Yii::getAlias('@app/views/layouts'));

        if(file_exists(\Yii::getAlias('@app/modules/'.$this->module->id.'/views/layouts'))){
            $layoutsModule = scandir(\Yii::getAlias('@app/modules/'.$this->module->id.'/views/layouts'));
            $layouts = ArrayHelper::merge($layoutsModule, $layouts);
        }

        foreach ($layouts as $key => $value) {
            if (in_array($value, ['.', '..']))
                unset($layouts[$key]);
            else {
                if($key == '')
                    continue;
                $layouts[$value] = $value;
                unset($layouts[$key]);
            }
        }

        return $layouts;
    }
}